language: java
script: "mvn cobertura:cobertura"
after_success:
  - bash <(curl -s https://codecov.io/bash)

env:
  global:
    - CODECOV_TOKEN=:6cb8d358-f2de-4b52-b554-0bd190f3c39f

branches:
  only:
    - master
    
CODECOV_TOKEN="ffc54244-f7fd-4106-947e-1c9d92e89a9c"
